//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDealDetailTable
    {
        public int OrderDealDetailID { get; set; }
        public int OrderID { get; set; }
        public int StockDealID { get; set; }
        public int Qty { get; set; }
        public double DealPrice { get; set; }
    
        public virtual StockDealTable StockDealTable { get; set; }
        public virtual OrderTable OrderTable { get; set; }
    }
}
