//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTable()
        {
            this.OrderDealDetailTables = new HashSet<OrderDealDetailTable>();
            this.OrderItemDetailTables = new HashSet<OrderItemDetailTable>();
        }
    
        public int OrderID { get; set; }
        public int OrderBy_UserID { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public int OrderTypeID { get; set; }
        public int DeliveryAddres_UserAddressID { get; set; }
        public string OrderReceivedBy_ContactNo { get; set; }
        public string OrderReceivedBy_FullName { get; set; }
        public int OrderStatusID { get; set; }
        public string Description { get; set; }
        public int ProcessBy_UserID { get; set; }
        public int OrderPaymentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDealDetailTable> OrderDealDetailTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemDetailTable> OrderItemDetailTables { get; set; }
        public virtual OrderPaymentTable OrderPaymentTable { get; set; }
        public virtual OrderStatusTable OrderStatusTable { get; set; }
        public virtual OrderTypeTable OrderTypeTable { get; set; }
        public virtual UserAddressTable UserAddressTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
