//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemDetailTable
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int StockItemID { get; set; }
        public int Qty { get; set; }
        public double UnitPrice { get; set; }
        public int DiscountID { get; set; }
        public double DiscountAmount { get; set; }
    
        public virtual DiscountTable DiscountTable { get; set; }
        public virtual StockItemTable StockItemTable { get; set; }
        public virtual OrderTable OrderTable { get; set; }
    }
}
