//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribeEmailTable
    {
        public int SubscribeEmailID { get; set; }
        public string SubscribeEmailAddress { get; set; }
        public bool SubscribeStatus { get; set; }
    }
}
