//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Orders
    {
        public int OrderID { get; set; }
        public int Customer_UserID { get; set; }
        public string Customer_UserName { get; set; }
        public System.DateTime Order_DateTime { get; set; }
        public int OrderTypeID { get; set; }
        public string OrderTpe { get; set; }
        public string Customer_FullName { get; set; }
        public string Customer_ContactNo { get; set; }
        public int OrderStatusID { get; set; }
        public string OrderStatus { get; set; }
        public string Description { get; set; }
        public int ProcessBy_UserID { get; set; }
        public string ProcessUserName { get; set; }
        public int OrderPaymentID { get; set; }
        public string OrderPaymentStatus { get; set; }
        public int DeliveryAddressID { get; set; }
        public string DeliveryAddress { get; set; }
    }
}
